<?php
/**
 * @file
 * Module file for signage uiowa panes module.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function signage_uiowa_panes_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_libraries_info().
 */
function signage_uiowa_panes_libraries_info() {
  $libraries['skycons'] = array(
    'name' => 'Skycons',
    'vendor url' => 'http://darkskyapp.github.io/skycons/',
    'download url' => 'https://github.com/darkskyapp/skycons',
    'version' => 1.0,
    'files' => array(
      'js' => array('skycons.js'),
    ),
  );
  return $libraries;
}
